In [ ]:
import numpy as np
import pandas as pd

module

In [3]:
list1 = [1, 2, 3, 4, 5]

print("list1:", list1)

list1: [1, 2, 3, 4, 5]


In [4]:
array1 = np.array(list1)
print("array1:", array1)

array1: [1 2 3 4 5]


In [6]:
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [7]:
toyPrices = np.array([5,8,3,6])
print(toyPrices - 2)

[3 6 1 4]


In [10]:
toyPrices = [5,8,3,6]

# print(toyPrices - 2) # Not possible with python lists
for i in range(len(toyPrices)):
    toyPrices[i] -= 2
print(toyPrices)

[3, 6, 1, 4]


In [ ]:
# Create a Series using a NumPy array of ages with the default numerical indices
ages = np.array([13, 25, 19])
series1 = pd.Series(ages)
print(series1)

0    13
1    25
2    19
dtype: int32


In [13]:
# Create a Series using a NumPy array of ages but customize the indices to be the names that correspond to each age
ages = np.array([13, 25, 19])
series1 = pd.Series(ages, index=["Emma", "Swetha", "Serajh"])
print(series1)

Emma      13
Swetha    25
Serajh    19
dtype: int32


In [15]:
ages = np.array([13, 25, 19])
print(ages)

[13 25 19]


In [ ]:
dataf = pd.DataFrame([
    ['John Smith', '123 Main St', 34],
    ['Jane Doe', '456 Maple Ave', 28],
    ['Joe Schmo', '789 Broadway', 51],
    ],
    columns=['name', 'address', 'age'])
# Print the DataFrame with default numerical indices
print(dataf)

# Print the DataFrame with a custom index
dataf.set_index('name')


         name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51


address  age
name                          
John Smith    123 Main St   34
Jane Doe    456 Maple Ave   28
Joe Schmo    789 Broadway   51